#!/usr/bin/env ansible-playbook
---
- hosts: backend
  tasks:
    - name: include version vars
      include_vars:
        file: backend-vars.yml

    - name: Install machine tools
      import_role:
        name: machine
      vars: {}

    - name: Install and setup Docker
      import_role:
        name: docker
      vars: {}

    - name: Install Redis
      import_role:
        name: redis
      vars: {}

    - name: Install and setup Postgres
      import_role:
        name: postgres
      vars:
        role_spec:
          users:
            first:
              name: '{{ ansible_env.USER }}'
              password: '{{ ansible_env.USER }}'

    - name: Install ruby
      import_role:
        name: ruby
      vars:
        role_spec:
          versions: '{{ ruby_versions }}'

    - name: Install node and requested node packages
      import_role:
        name: nodejs
      vars:
        role_spec:
          version: '{{ node_version }}'
          packages: '{{ node_packages }}'

    - name: Clone ros projects
      import_role:
        name: git
      vars:
        role_spec:
          project_dir: "{{ lookup('pipe', 'pwd') }}/.."
          repositories:
            ros:
              url: https://github.com/rails-on-services/ros-cli.git
              name: cli
            guides:
              url: https://github.com/rails-on-services/guides.git
            setup:
              url: https://github.com/rails-on-services/setup.git
            images:
              url: https://github.com/rails-on-services/images.git

    - name: Configure instance
      import_role:
        name: instance
      vars:
        project_dir: "{{ lookup('pipe', 'pwd') }}/../cli"

    - name: Insert aliases
      include_role:
        name: aliases
      vars:
        aliases_marker: ros-stuff
        aliases_block: |
          export RAILS_DATABASE_USER=vagrant
          export RAILS_DATABASE_PASSWORD=vagrant
