#!/usr/bin/env ansible-playbook
---
- hosts: backend
  tasks:
    - name: include version vars
      include_vars:
        file: cli-vars.yml

    - name: Install node and requested node packages
      import_role:
        name: nodejs
      vars:
        role_spec:
          version: '{{ node_version }}'
          packages: '{{ node_packages }}'

    - name: Clone ros projects
      import_role:
        name: git
      vars:
        role_spec:
          project_dir: "{{ lookup('pipe', 'pwd') }}/.."
          repositories:
            ros:
              url: https://github.com/rails-on-services/ros-cli.git
              name: cli
              version: "{{ ros_cli_version }}"

    - name: Configure cli
      import_role:
        name: cli
      vars:
        project_dir: "{{ lookup('pipe', 'pwd') }}/../cli"
