#!/usr/bin/env ansible-playbook
---
- name: Build ros Vagrant boxes
  hosts: localhost
  tasks:
    # - include_vars: projects-vars.yml
    - include_role:
        name: project
      vars:
        role_spec:
          name: ros
          # work_dir: builds
          xbase:
            distribution: debian
            version: buster64
          builds:
            - ros:
                # profile: build
                source: base
                disk_size: 50000
                # playbook: ros
                # target: ros
            - ros_rjayroach:
                # profile: build
                source: ros
                # target: ros-rjayroach
          # owner: rjayroach
          # # owner: {{ role_spec.owner }}
          # # aws_s3_bucket: {{ role_spec.aws_s3_bucket }}
          # aws_profile: default
          # # aws_region: {{ role_spec.aws_region }}
          # push: no
          # box_version: 0.0.1
          # bump_version: patch # minor, major
          ssh_username: test # {{ role_spec.ssh_username }}
          ssh_password: test # "{{ dbl }} 999999999999999999999 | random | string | to_uuid }}"
          # ssh_private_key_file: '{{ ansible_env.HOME }}/.ssh/id_rsa'
