#!/usr/bin/env ansible-playbook
---
- hosts: instance
  tasks:
    - name: Install and setup Docker
      import_role:
        name: docker
        tasks_from: 
      vars: {}

    - name: Install and setup Postgres
      import_role:
        name: postgres
      vars:
        role_spec:
          users:
            first:
              name: '{{ ansible_env.USER }}'
              password: '{{ ansible_env.USER }}'

    - name: Configure instance
      import_role:
        name: instance
      vars:
        project_dir: '{{ ansible_env.HOME }}/project'
