---
# Debian has a more complex install than mac
- name: Install binary on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install binary on MacOS
  homebrew:
    name: packer
    state: present
  when: ansible_os_family == 'Darwin'

- name: Ensure plugins directory exists
  file:
    path: '{{ spec.plugin_dir }}'
    state: directory

- name: Install plugins
  include_tasks: plugin.yml
  with_dict: '{{ spec.plugins }}'
  loop_control:
    loop_var: plugin
