---
- name: 'Prompt for {{ say }}'
  prompt:
    msg:
      say: '{{ say }}'
      ask: answer
      default: '{{ default | string }}'

- set_fact:
    role_spec: '{{ role_spec | combine({prompt_item: answer}) }}'
