version: 2.1
jobs:
  trigger_ros_images:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - run:
          name: "Trigger rails-on-services/images"
          command: |
            curl -X POST "https://circleci.com/api/v1.1/project/gh/rails-on-services/images/build?branch=master&circle-token=$CIRCLE_TOKEN"

workflows:
  build:
    jobs:
      - trigger_ros_images:
          filters:
            branches:
              only:
                - master
