---
- name: Install dependencies
  package:
    name: [xz-utils, curl]
    state: present
  become: yes

- name: Add repository
  shell: "curl -sL https://deb.nodesource.com/setup_{{ spec.version }} | bash -"
  args:
    warn: no
  become: yes

- name: Install node
  package:
    name: [nodejs]
    state: present
  become: yes
