---
base_env:
  provisioners:
    ansible:
      groups: ['packer-{{ role_spec.target }}']
      playbook_file: '{{ playbook_dir }}/packer.yml'
      type: ansible
      user: "{{ role_spec.ssh_username | default('vagrant') }}"
      ansible_env_vars:
        - "ANSIBLE_RETRY_FILES_ENABLED=false"

base_spec:
  scripts_dir: 'src/{{ role_spec.distribution }}'
  build_script: 'src/{{ role_spec.distribution }}/{{ role_spec.version }}/{{ role_spec.target }}-from-{{ role_spec.source }}.json'
  ssh_username: "{{ role_spec.ssh_username | default('vagrant') }}"
  box_version: 0.0.1
  vm_name: image

spec: "{{ base_spec | combine(role_spec, recursive=True) }}"
