---
base_spec:
  locale: en_US.UTF-8
  cache_valid_time: 86400
  packages:
    - nmap
    - tree
    - wget
    - htop

spec: '{{ base_spec | combine(dist_spec, recursive=True) | combine(role_spec, recursive=True) }}'
