#!/usr/bin/env ansible-playbook
---
- name: Configure project to build boxes
  hosts: localhost
  tasks:
    - include_role:
        name: project
      vars:
        role_spec:
          project:
            project_name: ros
            # work_dir: builds
          push:
            manifest: vagrant/json
            box_dir: vagrant/boxes
            aws:
              s3_bucket: perx-ros-boxes
              # Use a profile from ~/.aws/credentials or set AWS_* ENVs
              profile: default
              region: ap-southeast-1
          builds:
            - name: base
              distribution: debian
              version: buster64
              disk_size: 50000
            - name: generic
              source: base
              push: yes
              # playbook: devops # default is name, eg ros-generic
              # target: ros # default is name, eg ros-generic
            # - name: rjayroach
            # - source: generic
            # target: ros-rjayroach
            # bump_version: patch # minor, major
