---
base_spec:
  version: 1.4.2
  file: packer_1.4.2_linux_amd64
  plugin_dir: '{{ ansible_env.HOME }}/.packer.d/plugins'

  plugins:
    packer-post-processor-vagrant-s3:
      url: "https://github.com/lmars/packer-post-processor-vagrant-s3/releases/download/1.4.0/packer-post-processor-vagrant-s3-1.4.0-{{ 'darwin' if ansible_os_family == 'Darwin' else 'linux' }}-amd64.zip"
      dest: "packer-post-processor-vagrant-s3-1.4.0-{{ 'darwin' if ansible_os_family == 'Darwin' else 'linux' }}-amd64.zip"

spec: "{{ base_spec | combine(role_spec, recursive=True) }}"
