---
- name: Configure build images
  include_tasks: build.yml
  vars:
    build_spec: '{{ item }}'
  with_items: '{{ role_spec.builds }}'
  when: role_spec.builds is defined

- name: Copy Vagrantfile
  copy:
    src: Vagrantfile
    dest: '{{ spec.work_dir }}/Vagrantfile'
