---
- name: Create ROLE and grant dbcreate and superuser privileges
  postgresql_user:
    name: '{{ user.value.name | default(user.key) }}'
    password: '{{ user.value.password }}'
    role_attr_flags: 'SUPERUSER,CREATEDB'
  with_dict: '{{ spec.users }}'
  loop_control:
    loop_var: user
  become: postgres
