---
- name: Create ROLE and grant dbcreate and superuser privileges
  postgresql_user:
    name: '{{ user.value.name | default(user.key) }}'
    password: '{{ user.value.password }}'
    role_attr_flags: 'SUPERUSER,CREATEDB'
  with_dict: '{{ spec.users }}'
  loop_control:
    loop_var: user

- name: Create a new database
  postgresql_db:
    name: '{{ database.value.name | default(database.key) }}'
    owner: '{{ database.value.owner }}'
    state: present
  with_dict: '{{ spec.databases }}'
  loop_control:
    loop_var: database
