post_processors:
  vagrant:
    - '{{ build_env.post_processors.vagrant }}'
    - manifest: '{{ role_spec.push.manifest }}/{{ role_spec.project.project_name }}/{{ build_spec.name }}.json'
      box_dir: '{{ role_spec.push.box_dir }}/{{ role_spec.project.project_name }}/{{ build_spec.name }}'
      box_name: '{{ role_spec.project.project_name }}/{{ build_spec.name }}'
      version: '{{ box_version | default("0.0.1") }}'
      bucket: '{{ role_spec.push.aws.s3_bucket }}'
      profile: '{{ role_spec.push.aws.profile }}'
      region: '{{ role_spec.push.aws.region }}'
      type: vagrant-s3
