---
- name: Insert path to ros lib and exe
  include_role:
    name: aliases
  vars:
    type: profile
    aliases_marker: ros
    aliases_block: |
      export PATH=$PATH:{{ project_dir }}/exe

- name: install ros-cli dependencies
  shell: . /etc/profile && ~/.rbenv/shims/bundle install
  args:
    chdir: '{{ project_dir }}'
